version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo

parameters:
  instance:
    type: integer
    default: 1

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t myapp:latest .
      - run:
          name: Save image to workspace
          command: docker save myapp:latest -o myapp.tar
      - persist_to_workspace:
          root: ~/repo
          paths:
            - myapp.tar

  run-containers:
    executor: docker-executor
    parameters:
      instance:
        type: integer
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/repo
      - run:
          name: Load image
          command: docker load -i myapp.tar
      - run:
          name: Run 3 containers (auto-stop after 15m)
          command: |
            echo "🚀 Instance << parameters.instance >> running 3 containers (max 15m)"
            # Dùng timeout để kill tất cả sau 15 phút
            timeout 900 bash -c '
              pids=()
              for i in 1 2 3; do
                echo "Starting container $i"
                docker run --rm myapp:latest &
                pids+=($!)
              done
              wait
            '
            echo "⏹ Containers for instance << parameters.instance >> stopped after 15m"

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
      - run-containers:
          requires:
            - build
          matrix:
            parameters:
              instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
          # ⏱ Timeout toàn job (đặt ở cấp workflow)
          timeout_in_minutes: 15
